// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetFile(ctx context.Context, username string) (File, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
